In [1]:
#*****SAMPLING STRATEGY AND PRELIMINARY CLEANING (Talk to Ryan... cropping, how?) ---- PLACEHOLDER FOR EVERYTHING RYAN DID UP TO THIS POINT****

#Comment out any of the below installations if already installed.
# pip install tensorflow
# pip install keras
# pip install opencv-python 

In [13]:
#Import dependencies
#Load and inspect images using the Python Imaging Library (PIL)
from PIL import Image
import os
import numpy as np
import cv2
# from tensorflow import keras
#from keras.preprocessing.image import ImageDataGenerator
# from tensorflow.keras.preprocessing.image import ImageDataGenerator
import pickle
# from matplotlib import pyplot as plt

In [3]:
# Create a list of y_labels and their file paths
# The names are based on the name of the directory where the images were stored (i.e., dangerous, benign, guns, knives, etc... )

ylist = []
# Specify the directory containing the images
image_dir = "../Data/X_Ray Image DataSet"
# Iterate over the files in the directory
for root, dirs, files in os.walk(image_dir):
    for file in files:
        # Check if the file is a PNG image
        if file.endswith(".png"):
            # Construct the full file path
            file_path = os.path.join(root, file)
            
            # append name of directory to list
            ylist.append(root.split("\\")[-1])
            
            # Load the image
            image = Image.open(file_path)
            
            # Convert the image to grayscale if needed
            if image.mode != "L":
                image = image.convert("L")
                
            # # Display image information to understand what else needs to be done with it. For example, image sizes vary.
            # print("Image Path:", file_path)
            print("Image Size:", image.size)
            # print("Image Mode:", image.mode)
            # print("Image Format:", image.format)
            # print()

# convert list to np array
y=np.array(ylist)

Image Size: (900, 1430)
Image Size: (900, 1430)
Image Size: (900, 1430)
Image Size: (175, 173)
Image Size: (149, 149)
Image Size: (127, 125)
Image Size: (125, 125)
Image Size: (129, 129)
Image Size: (129, 129)
Image Size: (127, 127)
Image Size: (145, 147)
Image Size: (123, 123)
Image Size: (131, 131)
Image Size: (103, 101)
Image Size: (109, 111)
Image Size: (105, 107)
Image Size: (113, 113)
Image Size: (203, 203)
Image Size: (201, 201)
Image Size: (193, 193)
Image Size: (217, 217)
Image Size: (173, 173)
Image Size: (161, 163)
Image Size: (147, 149)
Image Size: (131, 131)
Image Size: (135, 135)
Image Size: (139, 139)
Image Size: (135, 135)
Image Size: (107, 107)
Image Size: (129, 131)
Image Size: (125, 125)
Image Size: (115, 113)
Image Size: (103, 103)
Image Size: (149, 147)
Image Size: (125, 125)
Image Size: (103, 101)
Image Size: (101, 101)
Image Size: (147, 147)
Image Size: (209, 207)
Image Size: (179, 179)
Image Size: (163, 165)
Image Size: (55, 55)
Image Size: (55, 55)
Image Size: 

Image Size: (105, 105)
Image Size: (139, 139)
Image Size: (131, 131)
Image Size: (121, 121)
Image Size: (131, 131)
Image Size: (131, 129)
Image Size: (129, 131)
Image Size: (121, 121)
Image Size: (123, 123)
Image Size: (125, 125)
Image Size: (127, 125)
Image Size: (123, 123)
Image Size: (119, 119)
Image Size: (111, 111)
Image Size: (103, 103)
Image Size: (177, 177)
Image Size: (175, 177)
Image Size: (173, 173)
Image Size: (171, 173)
Image Size: (167, 167)
Image Size: (163, 163)
Image Size: (149, 149)
Image Size: (149, 149)
Image Size: (191, 191)
Image Size: (201, 203)
Image Size: (203, 203)
Image Size: (199, 201)
Image Size: (191, 191)
Image Size: (181, 181)
Image Size: (165, 167)
Image Size: (167, 167)
Image Size: (99, 101)
Image Size: (99, 101)
Image Size: (149, 149)
Image Size: (145, 145)
Image Size: (121, 121)
Image Size: (123, 121)
Image Size: (123, 121)
Image Size: (121, 123)
Image Size: (145, 145)
Image Size: (143, 143)
Image Size: (137, 137)
Image Size: (131, 129)
Image Size: (

Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (2688, 2208)
Image Size: (621, 518)
Image Size: (926, 522)
Image Size: (1282, 528)
Image Size: (1415, 541)
Image Size: (1209, 554)
Image Size: (567, 708)
Image Size: (1001, 709)
Image Size: (1281, 719)
Image Size: (1313, 732)
Image Size: (1035, 744)
Image Size: (727, 782)
Image Size: (1144, 782)
Image Size: (1292, 781)
Image Size: (1182, 790)
Image Size: (798, 801)
Image Size: (966, 699)
Image Size: (1299, 698)
Image Size: (1311, 703)
Image Size: (1059, 715)
Image Size: (635, 725)
Image Size: (1141, 499)
Image Size: (1412, 497)
Image Size: (1336, 501)
Image Size: (989, 507)
Image S

Image Size: (612, 452)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Im

Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)
Image Size: (1258, 1258)


Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size: (861, 861)
Image Size:

Image Size: (585, 931)
Image Size: (555, 938)
Image Size: (492, 930)
Image Size: (474, 946)
Image Size: (799, 1005)
Image Size: (827, 989)
Image Size: (820, 977)
Image Size: (827, 987)
Image Size: (908, 927)
Image Size: (879, 951)
Image Size: (876, 972)
Image Size: (881, 1003)
Image Size: (878, 1000)
Image Size: (877, 931)
Image Size: (899, 982)
Image Size: (577, 894)
Image Size: (583, 892)
Image Size: (528, 884)
Image Size: (827, 866)
Image Size: (775, 917)
Image Size: (772, 892)
Image Size: (784, 931)
Image Size: (793, 933)
Image Size: (793, 908)
Image Size: (795, 897)
Image Size: (780, 936)
Image Size: (812, 954)
Image Size: (619, 1024)
Image Size: (611, 1002)
Image Size: (611, 1022)
Image Size: (563, 1003)
Image Size: (1011, 989)
Image Size: (994, 1029)
Image Size: (993, 1024)
Image Size: (994, 968)
Image Size: (1033, 1035)
Image Size: (992, 980)
Image Size: (997, 1033)
Image Size: (1007, 977)
Image Size: (983, 967)
Image Size: (923, 907)
Image Size: (941, 939)
Image Size: (947, 98

In [4]:
# Convert X variables/independent variables/Images to NumPy Arrays. Store these arrays into image_arrays.  
# The NumPy library provides support for working with
# numerical data in Python.
# Create an empty list to store the X/image arrays
image_arrays = []

# Iterate over the files in the directory
for root, dirs, files in os.walk(image_dir):
    for file in files:
        # Check if the file is a PNG image
        if file.endswith(".png"):
            # Construct the full file path
            file_path = os.path.join(root, file)
            
            # Load the image
            image = Image.open(file_path)
            
            # Convert the image to a NumPy array
            image_array = np.array(image)
            
            # Append the image array to the list
            image_arrays.append(image_array)
            
# Print the image arrays
for image_array in image_arrays:
    print(image_array)

[[234 233 235 ... 234 234 234]
 [234 234 235 ... 234 233 235]
 [234 235 234 ... 234 235 235]
 ...
 [235 235 235 ... 234 236 234]
 [236 235 236 ... 234 235 234]
 [235 234 234 ... 232 234 233]]
[[250 249 250 ... 249 249 250]
 [250 250 250 ... 249 250 250]
 [251 251 250 ... 251 250 250]
 ...
 [252 251 251 ... 250 250 249]
 [254 250 251 ... 250 250 250]
 [250 250 251 ... 248 250 250]]
[[239 237 238 ... 238 237 237]
 [237 238 238 ... 238 237 239]
 [238 240 238 ... 238 239 239]
 ...
 [239 239 240 ... 238 239 238]
 [240 239 239 ... 238 239 238]
 [239 239 239 ... 236 238 237]]
[[183 182 180 ...  12  13  16]
 [183 182 180 ...  14  15  16]
 [182 182 180 ...  15  16  17]
 ...
 [161 159 159 ... 100 102 103]
 [160 159 159 ... 100 101 103]
 [160 159 159 ... 101 102 103]]
[[162 161 161 ...  91  90  91]
 [162 161 161 ...  91  91  92]
 [162 161 160 ...  91  91  92]
 ...
 [144 141 139 ...  89  88  88]
 [144 141 138 ...  88  88  88]
 [144 140 138 ...  88  88  88]]
[[159 158 158 ... 109  90  72]
 [159 158

[[239 239 239 ... 243 239 239]
 [239 239 239 ... 241 239 239]
 [239 239 239 ... 239 239 239]
 ...
 [240 240 240 ... 241 240 240]
 [239 239 239 ... 239 240 240]
 [239 239 239 ... 239 240 240]]
[[236 235 235 ... 237 237 237]
 [236 235 235 ... 236 237 237]
 [236 235 235 ... 234 237 237]
 ...
 [235 235 236 ... 238 234 234]
 [234 235 236 ... 237 236 236]
 [234 235 236 ... 237 236 236]]
[[234 234 234 ... 238 238 238]
 [235 235 235 ... 237 237 237]
 [236 236 236 ... 235 236 236]
 ...
 [234 235 236 ... 234 236 236]
 [234 235 236 ... 238 237 237]
 [234 235 236 ... 238 237 237]]
[[238 238 238 ... 241 241 241]
 [239 239 239 ... 241 239 239]
 [240 240 240 ... 239 239 239]
 ...
 [241 241 241 ... 238 241 241]
 [237 237 238 ... 244 241 241]
 [237 237 238 ... 244 241 241]]
[[245 245 245 ... 244 246 246]
 [245 245 245 ... 244 243 243]
 [245 245 244 ... 244 242 242]
 ...
 [244 244 244 ... 245 246 246]
 [245 245 245 ... 244 245 245]
 [245 245 245 ... 244 245 245]]
[[242 241 240 ... 245 244 244]
 [243 242

In [5]:
# print # of images being stored (Excludes "Dangerous" category of images)
print(f" Converted {len(image_arrays)} images into numpy arrays")

 Converted 3386 images into numpy arrays


In [6]:
# Preprocess Images for Machine Learning.  
# Resize the images to a consistent size 
# Specify the target size
target_size = (224, 224)

# Initialize an empty list to store resized image arrays
resized_image_arrays = []

# Iterate over the image arrays
for image_array in image_arrays:
    # Convert the image array back to PIL image
    image = Image.fromarray(image_array)
    
    # Resize the image
    #resized_image = image.resize(target_size)
    resized_image = image.resize(target_size, resample = Image.LANCZOS)
    # Convert the resized image back to NumPy array
    resized_image_array = np.array(resized_image)#.astype(np.float32)
    # append image to resized_image_arrays
    resized_image_arrays.append(resized_image_array)
    
# Print the resized image array
print(resized_image_arrays)

[array([[235, 235, 235, ..., 234, 234, 234],
       [236, 235, 235, ..., 234, 235, 234],
       [235, 236, 235, ..., 235, 235, 235],
       ...,
       [236, 235, 235, ..., 234, 235, 234],
       [235, 235, 235, ..., 235, 235, 234],
       [235, 235, 235, ..., 234, 234, 234]], dtype=uint8), array([[251, 250, 251, ..., 250, 250, 250],
       [251, 251, 251, ..., 250, 250, 250],
       [251, 252, 252, ..., 250, 251, 251],
       ...,
       [251, 251, 251, ..., 250, 250, 250],
       [251, 251, 251, ..., 250, 251, 250],
       [251, 250, 251, ..., 250, 250, 250]], dtype=uint8), array([[238, 238, 238, ..., 237, 238, 238],
       [239, 239, 239, ..., 238, 238, 238],
       [239, 239, 239, ..., 238, 238, 238],
       ...,
       [239, 239, 239, ..., 238, 238, 238],
       [239, 239, 239, ..., 238, 238, 238],
       [239, 238, 239, ..., 238, 238, 238]], dtype=uint8), array([[183, 183, 181, ...,  12,  14,  16],
       [183, 182, 181, ...,  13,  15,  16],
       [183, 182, 181, ...,  15,  15, 

In [7]:
# Remove unwanted noise in the images to smooth them out (i.e., less grainy).
# When looking at denoising techniques, we settled on the OpenCV library.
# Normalize data  
# Create an empty list to store the denoised and normalized image arrays
denoised_image_arrays = []
#counter
i = 0

# Iterate over the image arrays
for image_array in resized_image_arrays:
    # print sets of 50 images
    if i%50==0:
        print(f"reading image number {i}")
    # Apply denoising filter and normalizing
    denoised_image_array = cv2.fastNlMeansDenoising(image_array, None, h=10, templateWindowSize=7, 
                                                searchWindowSize=21).astype(np.float32)/255
    
    denoised_image_array = denoised_image_array.reshape(image_array.shape)
    # print denoised_image_arraye
    #display(denoised_image_array)
    # Append the denoised image array to the list
    denoised_image_arrays.append(denoised_image_array)

    # add 1 to counter
    i=i+1
# Print the denoised image arrays
for i, denoised_image_array in enumerate(denoised_image_arrays):
    print(f"Values of denoised image {i}:", denoised_image_array)

reading image number 0
reading image number 50
reading image number 100
reading image number 150
reading image number 200
reading image number 250
reading image number 300
reading image number 350
reading image number 400
reading image number 450
reading image number 500
reading image number 550
reading image number 600
reading image number 650
reading image number 700
reading image number 750
reading image number 800
reading image number 850
reading image number 900
reading image number 950
reading image number 1000
reading image number 1050
reading image number 1100
reading image number 1150
reading image number 1200
reading image number 1250
reading image number 1300
reading image number 1350
reading image number 1400
reading image number 1450
reading image number 1500
reading image number 1550
reading image number 1600
reading image number 1650
reading image number 1700
reading image number 1750
reading image number 1800
reading image number 1850
reading image number 1900
reading i

Values of denoised image 1214: [[0.90588236 0.90588236 0.90588236 ... 0.91764706 0.91764706 0.91764706]
 [0.90588236 0.90588236 0.90588236 ... 0.91764706 0.91764706 0.91764706]
 [0.90588236 0.90588236 0.90588236 ... 0.91764706 0.91764706 0.91764706]
 ...
 [0.90588236 0.90588236 0.90588236 ... 0.90588236 0.90588236 0.90588236]
 [0.90588236 0.90588236 0.90588236 ... 0.90588236 0.90588236 0.90588236]
 [0.90588236 0.90588236 0.90588236 ... 0.90588236 0.90588236 0.90588236]]
Values of denoised image 1215: [[0.91764706 0.91764706 0.91764706 ... 0.92941177 0.92941177 0.92941177]
 [0.91764706 0.91764706 0.91764706 ... 0.92941177 0.92941177 0.92941177]
 [0.91764706 0.91764706 0.91764706 ... 0.92941177 0.92941177 0.92941177]
 ...
 [0.9254902  0.9254902  0.9254902  ... 0.9098039  0.9098039  0.9098039 ]
 [0.9254902  0.9254902  0.9254902  ... 0.9098039  0.9098039  0.9098039 ]
 [0.9254902  0.9254902  0.9254902  ... 0.9098039  0.9098039  0.9098039 ]]
Values of denoised image 1216: [[0.92156863 0.9215

Values of denoised image 2447: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Values of denoised image 2448: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Values of denoised image 2449: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Values of denoised image 2450: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Values of denoised image 2451: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Values of denoised image 2452: [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1

In [8]:
# create path for pickle file
path = '../Data/x-ray.pkl'

# Open a new file named 'img.pkl' with write permission
with open(path, 'wb') as file:
    # Use pickle.dump to store the list of images
    pickle.dump(denoised_image_arrays, file)

In [9]:
#print y values
y

array(['Benign', 'Benign', 'Benign', ..., 'Throwing Star',
       'Throwing Star', 'Throwing Star'], dtype='<U13')

In [10]:
# Save y to a CSV file
np.savetxt('../Data/Y_Labels/y_labels.csv', y, fmt='%s', delimiter=',')

In [21]:
#checking for imbalnce data
unique_values, counts = np.unique(y, return_counts=True)

# Print unique values and their counts
for value, count in zip(unique_values, counts):
    print(f"{value}: {count}")

Benign: 909
Guns: 624
Knives: 776
Razor Blades: 403
Throwing Star: 674
