In [2]:
#Load and inspect images using the Python Imaging Library (PIL)
from PIL import Image
import os


# Specify the directory containing the images
image_dir = "/Users/ryanbusman/Desktop/Final_Project_X_RAy/Data/X_Ray Image DataSet"

# Iterate over the files in the directory
for root, dirs, files in os.walk(image_dir):
    for file in files:
        # Check if the file is a PNG image
        if file.endswith(".png"):
            # Construct the full file path
            file_path = os.path.join(root, file)
            
            # Load the image
            image = Image.open(file_path)
            
            # Display image information
            print("Image Path:", file_path)
            print("Image Size:", image.size)
            print("Image Mode:", image.mode)
            print("Image Format:", image.format)
            print()



Image Path: /Users/ryanbusman/Desktop/Final_Project_X_RAy/Data/X_Ray Image DataSet/Razor Blades/B0004_0005.png
Image Size: (850, 850)
Image Mode: L
Image Format: PNG

Image Path: /Users/ryanbusman/Desktop/Final_Project_X_RAy/Data/X_Ray Image DataSet/Razor Blades/B0073_0010.png
Image Size: (1688, 1692)
Image Mode: L
Image Format: PNG

Image Path: /Users/ryanbusman/Desktop/Final_Project_X_RAy/Data/X_Ray Image DataSet/Razor Blades/B0051_0014.png
Image Size: (407, 407)
Image Mode: L
Image Format: JPEG

Image Path: /Users/ryanbusman/Desktop/Final_Project_X_RAy/Data/X_Ray Image DataSet/Razor Blades/B0051_0028.png
Image Size: (407, 407)
Image Mode: L
Image Format: JPEG

Image Path: /Users/ryanbusman/Desktop/Final_Project_X_RAy/Data/X_Ray Image DataSet/Razor Blades/B0065_0002.png
Image Size: (2136, 1712)
Image Mode: L
Image Format: PNG

Image Path: /Users/ryanbusman/Desktop/Final_Project_X_RAy/Data/X_Ray Image DataSet/Razor Blades/B0065_0016.png
Image Size: (2136, 1712)
Image Mode: L
Image For

In [3]:
#Convert Images to NumPy Arrays.  The NumPy library provides support for working with numerical data in Python.
import numpy as np

# Create an empty list to store the image arrays
image_arrays = []

# Iterate over the files in the directory
for root, dirs, files in os.walk(image_dir):
    for file in files:
        # Check if the file is a PNG image
        if file.endswith(".png"):
            # Construct the full file path
            file_path = os.path.join(root, file)
            
            # Load the image
            image = Image.open(file_path)
            
            # Convert the image to a NumPy array
            image_array = np.array(image)
            
            # Append the image array to the list
            image_arrays.append(image_array)
            
# Print the image arrays
for image_array in image_arrays:
    print(image_array)


[[238 237 238 ... 236 237 237]
 [237 237 238 ... 237 237 237]
 [237 238 236 ... 236 237 237]
 ...
 [237 237 238 ... 237 238 237]
 [237 238 237 ... 238 239 237]
 [237 237 238 ... 237 238 236]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[226 226 226 ... 226 226 226]
 [226 226 226 ... 226 226 226]
 [226 226 226 ... 226 226 226]
 ...
 [226 226 226 ... 224 224 224]
 [226 226 226 ... 224 224 224]
 [226 226 226 ... 224 224 224]]
[[223 224 225 ... 225 225 225]
 [223 224 225 ... 225 225 225]
 [223 224 225 ... 225 225 225]
 ...
 [224 224 224 ... 225 225 224]
 [223 223 223 ... 225 224 223]
 [223 223 223 ... 225 224 223]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255

In [4]:

#Preprocess Images for Machine Learning.  Resize the images to a consistent size and normalize the pixel values.
from PIL import Image
# Specify the target size
target_size = (224, 224)

# Iterate over the image arrays
for image_array in image_arrays:
    # Convert the image array back to PIL image
    image = Image.fromarray(image_array)
    
    # Resize the image
    resized_image = image.resize(target_size)
    
    # Convert the resized image back to NumPy array
    resized_image_array = np.array(resized_image)
    
    # Print the resized image array
    print(resized_image_array)



[[237 238 237 ... 236 237 237]
 [237 237 238 ... 237 237 237]
 [237 237 238 ... 237 236 236]
 ...
 [237 238 237 ... 237 237 237]
 [238 237 237 ... 237 237 237]
 [237 238 237 ... 237 237 237]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[226 226 226 ... 226 226 226]
 [226 226 226 ... 226 226 226]
 [226 226 226 ... 226 226 226]
 ...
 [226 226 226 ... 225 224 224]
 [226 226 226 ... 225 224 224]
 [226 226 226 ... 225 224 224]]
[[223 225 223 ... 225 225 225]
 [223 225 223 ... 225 225 225]
 [223 225 223 ... 224 224 224]
 ...
 [225 225 225 ... 227 226 224]
 [224 224 224 ... 226 225 224]
 [223 223 223 ... 225 225 223]]
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[[255 255 255 ... 255 255 255]
 [255 255

In [5]:
#pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [6]:
#pip install keras

Note: you may need to restart the kernel to use updated packages.


In [7]:
#pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [8]:
import cv2
#Remove unwanted noise in the images - research denoising techniques settled on the OpenCV library.
# Create an empty list to store the denoised image arrays
denoised_image_arrays = []

# Iterate over the image arrays
for image_array in image_arrays:
    # Apply denoising filter
    denoised_image_array = cv2.fastNlMeansDenoising(image_array, None, h=10, templateWindowSize=7, searchWindowSize=21)
    
    # Append the denoised image array to the list
    denoised_image_arrays.append(denoised_image_array)
    
# Print the denoised image arrays
for denoised_image_array in denoised_image_arrays:
    print(denoised_image_array)


In [ ]:
#crop out the irrevelant parts of the image
from PIL import Image

# Open the image
image = Image.open("your_image.jpg")

# Define the coordinates for cropping (left, upper, right, lower)
crop_coords = (100, 100, 400, 400)

# Crop the image
cropped_image = image.crop(crop_coords)

# Display the cropped image
cropped_image.show()


In [1]:
# Specify the directory to save the augmented images
save_dir = "/Users/ryanbusman/Desktop/Final_Project_X_RAy/Data"

# Iterate over the augmented image arrays
for i, augmented_image_array in enumerate(augmented_image_arrays):
    # Convert the augmented image array to PIL image
    augmented_image = Image.fromarray(augmented_image_array)
    
    # Construct the file path to save the augmented image
    file_path = os.path.join(save_dir, f"augmented_image_{i}.png")
    
    # Save the augmented image to disk
    augmented_image.save(file_path)
    
    # Print the file path of the saved augmented image
    print("Saved augmented image:", file_path)


NameError: name 'augmented_image_arrays' is not defined

In [ ]:
#convert the images to grey scale if needed.
# Iterate over the image arrays
for image_array in image_arrays:
    # Convert the image array back to PIL image
    image = Image.fromarray(image_array)
    
    # Check if the image is not already in grayscale
    if image.mode != 'L':
        # Convert the image to grayscale
        image = image.convert('L')
    
    # Convert the grayscale image back to NumPy array
    grayscale_image_array = np.array(image)
    
    # Print the grayscale image array
    print(grayscale_image_array)
